POST http://localhost:5000/
Content-Type: application/json

{
  "n_threads": 2,
  "urls": [
    "http://4chan.org/",
    "http://golang.org/"
  ]
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "urls": [
      "https://developers.google.com/earth-engine/tutorials/tutorial_api_04"
  ]
}

###
GET http://localhost:5000/status/7b5af6c0-a9ea-11eb-8872-0242ac110003
Accept: application/json

###
GET http://localhost:5000/result/7b5af6c0-a9ea-11eb-8872-0242ac110003
Accept: application/json

###
GET http://localhost:5000/statistics

###
